/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle_example_kotlin

import java.io.IOException

class App {
    val runTest: String
        get() = try {
            val text = App::class.java.getResource("/test.txt")!!.readText()
            val numbers =
                text.split("\n")
                    .filter(String::isNotBlank)
                    .map(String::trim)
                    .map(String::toInt)
                    .toIntArray()
            val current = System.currentTimeMillis()
            Mergesort.mergeSort(numbers)
            println("Time: " + (System.currentTimeMillis() - current))
            numbers.joinToString()
        } catch (e: IOException) {
            throw RuntimeException(e)
        }

}
fun main() {
    println(App().runTest)
}