/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle_example;

import com.google.common.io.Resources;

import java.io.IOException;
import java.net.URL;
import java.nio.charset.StandardCharsets;

public class App {
    public String getGreeting() {
        try {
            URL url = Resources.getResource("test.txt");
            String text = Resources.toString(url, StandardCharsets.UTF_8);
            System.out.println(text);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
